VERSION = "0.0.1"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
ACCOUNTS = []

[DOCUMENTATION]
ORG_NAME = "Undefined"
ORG_DBA = "Pintheon Node"
ORG_URL = "https://pintheon.cloud"
ORG_OFFICIAL_EMAIL = "Undefined"
ORG_SUPPORT_EMAIL = "Undefined"
ORG_TWITTER = "Undefined"
ORG_DESCRIPTION = "Undefined"
